icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: shaolinOP
packager: shaolinOP
license: GPLv3
url: https://github.com/shaolinOP/my-app

requires:
  - mpv-libs
  - libappindicator

display_name: Elythra Music

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true